#!/usr/bin/env bash
# Negative test: kernel tamper.
#
# Design: tampered flash_image.hex is PRE-GENERATED by build.sh and lives
# in this directory's tempered_flash_image/. We just stage that hex into
# Chipyard's Verilator working directory, run the regular SecureBootConfig
# sim, then restore the good hex. The main repo's flash_image/*.bin is
# never modified.
#
# Run once first if tempered_flash_image/ doesn't exist:
#   bash tests/test_tempering_kernel/build.sh
#
# Expected sim output:
#   - "boot status register = 0x00000008"
#   - "check_and_load_kernel failed (bit 3)"
#   - "Verilog $finish"
#   - NO "kernel started successfully rocket"
#   - NO "bad kernel!"   (the malicious payload must NOT execute)

set -eo pipefail
# Not using `set -u`: Chipyard's conda activate scripts reference some
# BACKUP_* variables that may be unset on first activation.

TEST_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
REPO=$(cd "$TEST_DIR/../.." && pwd)
export CONDA_BACKUP_RISCV=${CONDA_BACKUP_RISCV:-}
source "$REPO/.env"

GOOD_HEX="$REPO/flash_image/flash_image.hex"
TAMPERED_HEX="$TEST_DIR/tempered_flash_image/flash_image.hex"
SIM_HEX="$CHIPYARD_HOME/sims/verilator/flash_image/flash_image.hex"
SIMULATOR="$CHIPYARD_HOME/sims/verilator/simulator-chipyard.harness-SecureBootConfig"
KERNEL="$REPO/software/kernel/kernel.riscv"
RECOVERY="$REPO/software/recovery/recovery.riscv"

# Sanity
[ -x "$SIMULATOR" ]    || { echo "FAIL: simulator not built at $SIMULATOR"; exit 1; }
[ -f "$TAMPERED_HEX" ] || { echo "FAIL: tampered hex missing at $TAMPERED_HEX"; echo "      Run: bash $TEST_DIR/build.sh"; exit 1; }
[ -f "$GOOD_HEX" ]     || { echo "FAIL: original (good) hex missing at $GOOD_HEX"; exit 1; }
[ -f "$SIM_HEX" ]      || { echo "FAIL: chipyard staging hex missing at $SIM_HEX"; exit 1; }

# ── restore-on-exit safety net ──────────────────────────────────────────
LOG=$(mktemp)
cleanup() {
    cp -p "$GOOD_HEX" "$SIM_HEX"
    rm -f "$LOG"
}
trap cleanup EXIT

# ── stage tampered hex into Chipyard's Verilator working dir ─────────────
echo "  staging tampered hex (bad kernel) into Chipyard..."
cp -p "$TAMPERED_HEX" "$SIM_HEX"

# ── run sim ─────────────────────────────────────────────────────────────
# Notes on the sim invocation (same as the other tempering tests):
#   - +payload= for recovery.riscv (FESVR ignores positional targs[1+])
#   - no stdbuf -oL (Verilator C++ iostreams incompatible)
#   - no timeout wrapping (combining timeout + file redirect loses output)
echo "  running sim (~1-2 min)..."
cd "$CHIPYARD_HOME/sims/verilator"
"$SIMULATOR" "+payload=$RECOVERY" "$KERNEL" > "$LOG" 2>&1
SIM_EXIT=$?

# ── verdict ─────────────────────────────────────────────────────────────
echo
echo "── sim output ───────────────────────────────────────────────────"
cat "$LOG"
echo "─────────────────────────────────────────────────────────────────"

PASS=true
EVIDENCE=""

# Signal 1: kernel banner — must be ABSENT (BootROM rejected the image)
if grep -q "kernel started successfully" "$LOG"; then
    echo "FAIL: kernel booted normally — Stage 3 (check_and_load_kernel) did NOT catch the tamper"
    PASS=false
else
    EVIDENCE="$EVIDENCE\n  ✓ kernel banner absent"
fi

# Signal 1b: bad_kernel's payload MUST NOT have run — if "bad kernel!" appears
# in the log, the malicious binary executed, which means secure boot FAILED.
if grep -q "bad kernel!" "$LOG"; then
    echo "CRITICAL FAIL: 'bad kernel!' appears in log — the malicious payload EXECUTED."
    echo "               Stage 3 did not reject the tampered kernel before mret."
    PASS=false
else
    EVIDENCE="$EVIDENCE\n  ✓ malicious payload did NOT execute ('bad kernel!' absent)"
fi

# Signal 2: recovery banner reached
if grep -q "in recovery mode" "$LOG"; then
    EVIDENCE="$EVIDENCE\n  ✓ recovery firmware reached (printed 'something went wrong, in recovery mode')"
fi

# Signal 3: SR readout = 0x00000008 (SR_LOAD_KERNEL bit 3)
if grep -q "boot status register = 0x00000008" "$LOG"; then
    EVIDENCE="$EVIDENCE\n  ✓ recovery confirmed SR = 0x00000008 (SR_LOAD_KERNEL bit set)"
fi

# Signal 4: per-stage diagnostic
if grep -q "check_and_load_kernel failed" "$LOG"; then
    EVIDENCE="$EVIDENCE\n  ✓ recovery decoded failure as Stage 3 (check_and_load_kernel)"
fi

# Signal 5: clean Verilog $finish (sim_exit=0)
if grep -q "Verilog \$finish" "$LOG" && [ "$SIM_EXIT" -eq 0 ]; then
    EVIDENCE="$EVIDENCE\n  ✓ sim exited cleanly via \$finish (sim_exit=0)"
fi

# Fallback diagnostic for known failure modes
if grep -qE "exit code =[[:space:]]+128\b" "$LOG"; then
    echo "FAIL: BootROM mret_trap_exit fired (exit code 0x80) — recovery.riscv not loaded at 0x80100000."
    echo "      Check that recovery is passed via +payload=, not as positional arg."
    PASS=false
fi

if $PASS; then
    echo -e "PASS:$EVIDENCE"
    exit 0
else
    exit 1
fi
