#!/usr/bin/env bash
# Negative test: pubkey tamper.
#
# Design: tampered flash_image.hex is PRE-GENERATED by build.sh and lives in
# this directory's tempered_flash_image/. We just stage that hex into
# Chipyard's Verilator working directory, run the regular SecureBootConfig
# sim, then restore the good hex. The main repo's flash_image/*.bin is
# never modified.
#
# Run once first if tempered_flash_image/ doesn't exist:
#   bash tests/test_tempering_public_key/build.sh
#
# Expected sim output:
#   - "boot status register = 0x00000002"
#   - "check_public_key failed (bit 1)"
#   - "Verilog $finish"
#   - NO "kernel started successfully rocket"

set -eo pipefail
# Not using `set -u`: Chipyard's conda activate scripts reference some
# BACKUP_* variables that may be unset on first activation.

# ── locate repo + sim binary ────────────────────────────────────────────
TEST_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
REPO=$(cd "$TEST_DIR/../.." && pwd)
export CONDA_BACKUP_RISCV=${CONDA_BACKUP_RISCV:-}
source "$REPO/.env"

GOOD_HEX="$REPO/flash_image/flash_image.hex"
TAMPERED_HEX="$TEST_DIR/tempered_flash_image/flash_image.hex"
SIM_HEX="$CHIPYARD_HOME/sims/verilator/flash_image/flash_image.hex"
SIMULATOR="$CHIPYARD_HOME/sims/verilator/simulator-chipyard.harness-SecureBootConfig"
KERNEL="$REPO/software/kernel/kernel.riscv"
RECOVERY="$REPO/software/recovery/recovery.riscv"

# Sanity
[ -x "$SIMULATOR" ]    || { echo "FAIL: simulator not built at $SIMULATOR"; exit 1; }
[ -f "$TAMPERED_HEX" ] || { echo "FAIL: tampered hex missing at $TAMPERED_HEX"; echo "      Run: bash $TEST_DIR/build.sh"; exit 1; }
[ -f "$GOOD_HEX" ]     || { echo "FAIL: original (good) hex missing at $GOOD_HEX"; exit 1; }
[ -f "$SIM_HEX" ]      || { echo "FAIL: chipyard staging hex missing at $SIM_HEX"; exit 1; }

# ── restore-on-exit safety net ──────────────────────────────────────────
# If anything below (sim crash, ctrl-C) leaves the chipyard staging file
# pointing at the tampered hex, this trap restores the good one. The
# repo's own flash_image/ is never touched, so there's no other state
# to worry about.
LOG=$(mktemp)
cleanup() {
    cp -p "$GOOD_HEX" "$SIM_HEX"
    rm -f "$LOG"
}
trap cleanup EXIT

# ── stage tampered hex into Chipyard's Verilator working dir ─────────────
echo "  staging tampered hex into Chipyard..."
cp -p "$TAMPERED_HEX" "$SIM_HEX"

# ── run sim ─────────────────────────────────────────────────────────────
# Critical: recovery.riscv MUST be passed via +payload=, not as a positional
# argument. FESVR's load_program only loads targs[0] (kernel); positional
# targs[1..] are silently ignored. Without +payload, recovery.riscv is not
# loaded into DRAM → BootROM's mret to 0x80100000 traps → mret_trap_exit
# safety stub fires → exit code 0x80.
#
# Do NOT use `stdbuf -oL`: Verilator C++ iostreams incompatible with
# libstdbuf's stdio override.
# Do NOT wrap with `timeout`: combining timeout + file redirect loses sim
# output to the file (cause unclear; reproducible). Outer `timeout 360
# bash run.sh` works as protection if needed.
echo "  running sim (~1-2 min)..."
cd "$CHIPYARD_HOME/sims/verilator"
"$SIMULATOR" "+payload=$RECOVERY" "$KERNEL" > "$LOG" 2>&1
SIM_EXIT=$?

# ── verdict ─────────────────────────────────────────────────────────────
echo
echo "── sim output ───────────────────────────────────────────────────"
cat "$LOG"
echo "─────────────────────────────────────────────────────────────────"

PASS=true
EVIDENCE=""

# Signal 1: kernel banner — must be ABSENT (BootROM rejected the image)
if grep -q "kernel started successfully" "$LOG"; then
    echo "FAIL: kernel booted normally — Stage 1 (check_public_key) did NOT catch the tamper"
    PASS=false
else
    EVIDENCE="$EVIDENCE\n  ✓ kernel banner absent"
fi

# Signal 2: recovery banner reached
if grep -q "in recovery mode" "$LOG"; then
    EVIDENCE="$EVIDENCE\n  ✓ recovery firmware reached (printed 'something went wrong, in recovery mode')"
fi

# Signal 3: SR readout = 0x00000002 (SR_PUBLIC_KEY bit)
if grep -q "boot status register = 0x00000002" "$LOG"; then
    EVIDENCE="$EVIDENCE\n  ✓ recovery confirmed SR = 0x00000002 (SR_PUBLIC_KEY bit set)"
fi

# Signal 4: per-stage diagnostic
if grep -q "check_public_key failed" "$LOG"; then
    EVIDENCE="$EVIDENCE\n  ✓ recovery decoded failure as Stage 1 (check_public_key)"
fi

# Signal 5: clean Verilog $finish (sim_exit=0)
if grep -q "Verilog \$finish" "$LOG" && [ "$SIM_EXIT" -eq 0 ]; then
    EVIDENCE="$EVIDENCE\n  ✓ sim exited cleanly via \$finish (sim_exit=0)"
fi

# Fallback diagnostic for known failure modes
if grep -qE "exit code =[[:space:]]+128\b" "$LOG"; then
    echo "FAIL: BootROM mret_trap_exit fired (exit code 0x80) — recovery.riscv not loaded at 0x80100000."
    echo "      Check that recovery is passed via +payload=, not as positional arg."
    PASS=false
fi

if $PASS; then
    echo -e "PASS:$EVIDENCE"
    exit 0
else
    exit 1
fi
